export const data = [
  {
    id: 1,
    tipo: "Ativo",
    cnpj: "08.753.063/0001-20",
    razaoSocial: "Stanton, Feeney and Pacocha",
    emailContato: "ggolling0@list-manage.com",
    pessoaContato: "Gar Golling",
  },
  {
    id: 2,
    tipo: "Inativo",
    cnpj: "58.089.031/0001-40",
    razaoSocial: "Spencer Group",
    emailContato: "jdanbury1@omniture.com",
    pessoaContato: "Joanne Danbury",
  },
  {
    id: 3,
    tipo: "Eventual",
    cnpj: "96.438.030/0001-53",
    razaoSocial: "Sauer-Thiel",
    emailContato: "echoffin2@youtube.com",
    pessoaContato: "Elisha Choffin",
  },
  {
    id: 4,
    tipo: "Doméstico",
    cnpj: "68.621.856/0001-18",
    razaoSocial: "Harris LLC",
    emailContato: "mdaber3@boston.com",
    pessoaContato: "Marty Daber",
  },
  {
    id: 5,
    tipo: "Ativo",
    cnpj: "27.531.186/0001-61",
    razaoSocial: "Green, Spinka and Jacobson",
    emailContato: "llorait4@cloudflare.com",
    pessoaContato: "Leon Lorait",
  },
  {
    id: 6,
    tipo: "Inativo",
    cnpj: "78.234.392/0001-40",
    razaoSocial: "Runolfsson, Nienow and Koelpin",
    emailContato: "cduinbleton5@reverbnation.com",
    pessoaContato: "Cirillo Duinbleton",
  },
  {
    id: 7,
    tipo: "Eventual",
    cnpj: "68.020.230/0001-56",
    razaoSocial: "Simonis, Hodkiewicz and Treutel",
    emailContato: "ijimenez6@phoca.cz",
    pessoaContato: "Iver Jimenez",
  },
  {
    id: 8,
    tipo: "Doméstico",
    cnpj: "33.350.162/0001-09",
    razaoSocial: "Bogan, Nienow and Schultz",
    emailContato: "jkasher7@1und1.de",
    pessoaContato: "Jess Kasher",
  },
  {
    id: 9,
    tipo: "Ativo",
    cnpj: "52.250.484/0001-20",
    razaoSocial: "Beahan-Carroll",
    emailContato: "dfentem8@drupal.org",
    pessoaContato: "Desirae Fentem",
  },
  {
    id: 10,
    tipo: "Doméstico",
    cnpj: "39.738.943/0001-51",
    razaoSocial: "Bergnaum and Sons",
    emailContato: "astoade9@about.com",
    pessoaContato: "Auroora Stoade",
  },
];